meta_product_name: "Cocktail o'clock!"
meta_title: "Cocktail o'clock! - Tick, tock, it's cocktail o'clock"
meta_description: "Time to prepare your awesome cocktail"
meta_image: "cover.png" # should exist in `app/assets/images/`
